### ISSUE TITLE
npm ERR! 404 Not found : gatsby-plugin-seo-export

### ISSUE THREAD

**Issue by spences10** [clipchamp/gatsby-plugin-seo-export#1]
Hey, I was going to implement this and got this.

![image](https://user-images.githubusercontent.com/234708/55378802-73146700-5512-11e9-9746-235d3b1d963d.png)

**Comment by i001962** [comment]
> Hey, I was going to implement this and got this.
> 
> ![image](https://user-images.githubusercontent.com/234708/55378802-73146700-5512-11e9-9746-235d3b1d963d.png)

I did manage to get this to work as a local plugin without too much effort by following the setup in this tutorial https://www.gatsbyjs.org/docs/pixabay-source-plugin-tutorial/

Never did get the seo script in package.json to work so I just set the variable and then ran gatsby build

**Comment by me4502** [comment]
Sorry, just fixed it. The correct package is `@clipchamp/gatsby-plugin-seo-export`.
